### ISSUE TITLE
fix Controller not found error while renaming attachment

### ISSUE THREAD

**Issue by the-old-ma** [Chaosmeister/EAR#11]
this is happening due to the inconsistency of package name and name spaces,

1. Change the package name to EAR, 
On plugin.php, change the name space to
`namespace Kanboard\Plugin\EAR;`

2. filename, Controller\AttachmentHandler.php change name space to 
`namespace Kanboard\Plugin\EAR\Controller;`

3. On template files, the plugin name shall also be EAR

**Comment by Chaosmeister** [comment]
heyo
currently there's no usage of "EAR" in my code, at least in the official release.

did you clone the repo into your plugin directory?

**Comment by the-old-ma** [comment]
i guess i just downloaded the 1.1.2 release., didn't clone the code.

**Comment by Chaosmeister** [comment]
does it work correctly now?

there's an inconsistency between the repo name and the actual plugin name(space)

I could adjust it

**Comment by the-old-ma** [comment]
i already corrected on my applications. all is good now, thank you for asking.
