### ISSUE TITLE
Add to Project Overview

### ISSUE THREAD

**Issue by eduardomozart** [Chaosmeister/EAR#3]
I tried to edit the plugin to include it's rename functionality to Project Attachments (Overview page) but with no success.
I could add the button to the Project Overview page adding the following hooks at Plugin.php file:

```
        $this->template->hook->attach("template:project-overview:images:dropdown", "EAR:rename/attachment");
        $this->template->hook->attach("template:project-overview:documents:dropdown", "EAR:rename/attachment");
```

Can you please add this functionality to this project? Thank you!

**Comment by Chaosmeister** [comment]
sure thing!  thanks for the hint

**Comment by Chaosmeister** [comment]
I added a new release with these two lines:

https://github.com/Chaosmeister/EAR/releases/tag/1.1.1

should be updatable with the kanboard plugin-installer as soon as https://github.com/kanboard/website/pull/315 is merged

**Comment by eduardomozart** [comment]
Adding the two lines above are enough to show the Rename link to project attachments, but it's unable to rename them. I believe it's necessary to change the plugin query to the database as well for it to rename the attachment into the project attachment database.

**Comment by Chaosmeister** [comment]
ah  well I need to check behind the scenes then

**Comment by Chaosmeister** [comment]
I just updated the release.

renaming attachments in the project overview now works for images.
another hook is necessary for the other attached documents.
[the pull request is here](https://github.com/kanboard/kanboard/pull/5027)

**Comment by aljawaid** [comment]
@Chaosmeister I just found this.... this missing hook could be why my renaming doesnt work. could you please add compatibility version for the plugin in your plugin file?
