### ISSUE TITLE
Please correct the namespace and add compatibility

### ISSUE THREAD

**Issue by aljawaid** [Chaosmeister/EAR#4]
hello

- the namespace is not matching the plugin which is why the update button doesnt work.
- please add a compatibility label for the version as the renaming doesnt work for everybody (i think its the missing hook but I need to check further)

**Comment by aljawaid** [comment]
It definitely doesn't work on 1.2.20

**Comment by Chaosmeister** [comment]
heyo, sure thing,  you're absolutely correct

**Comment by Chaosmeister** [comment]
I adjusted the compatibility but I have trouble finding out whats wrong with the namespace.
Can you give me a hint on what is wrong?

**Comment by aljawaid** [comment]
> I adjusted the compatibility but I have trouble finding out whats wrong with the namespace. Can you give me a hint on what is wrong?

it didnt update when there was an update available.. you called it `EAR` but you named it `Enable attachment renaming` - they both must match

**Comment by Chaosmeister** [comment]
ahh
I'll check it out
