### ISSUE TITLE
Missmatch Plugin Folder Name and Namespace

### ISSUE THREAD

**Issue by JustFxDev** [Chaosmeister/EAR#5]
Hi,

since 1.1.2 the PlugIn does not show up in the list of installed plugins. There is min. a mismatch in Plugin.php regarding the foldername of the plugin.

I've installed via the function inside Kanboard, not by cloning or manual copy.

I renamed it. After that the plugin is listed again, but i have still none of the buttons to view or rename.

Cheers, fx

**Comment by JustFxDev** [comment]
Added a branch and a pull request which should fix this issue.

Cheers, fx

**Comment by JustFxDev** [comment]
Hi!

I would kindly like to ask to add my pull request from 16.12.2022 and release an actual version to the plugin repository of Kanboard.

This fixes a serious issue and allows the future use of this plugin.

This would be great!

Thanks in advance, Fx

**Comment by Chaosmeister** [comment]
It should finally work now

The release is corrected as well
