### ISSUE TITLE
Still listed after installed

### ISSUE THREAD

**Issue by salazarjoelo** [Chaosmeister/EAR#7]
Hi there. Thanks for this plugin @Chaosmeister!
I installed it but still appears as "not installed" in plugins kanboard instance directory, so I am just reporting this issue. It runs ok, just appears as not installed.

**Comment by Chaosmeister** [comment]
Hi,
thanks for the hint!

I failed to update the release correctly. it's fixed now.

Unfortunately you need to delete the EAR directory from your plugins directory manually.

**Comment by salazarjoelo** [comment]
Thanks to You for your great Job. I have it running correctly and listed in
the installed plugins directory.

*"Gracias por pensar en un Medio Ambiente Saludable"*
Atenta y Respetuosamente

Joel Salazar Ramírez


   - Lic. en Derecho
   - Certificación en Data Science en Microsoft
   - Honor code certificate “Big Data and Social Physics” *MIT*
   - Honor code certificate "Data Analytics and Learning" *UT Arlington*
   - Honor code certificate “Behavioural Economics in Action” *University
   of Toronto*
   - Honor code certificate “Solving complex problems” *Delft University of
   technology* edX
   - Honor code certificate “Leaders of Learning” *Harvard* edX
   - Honor code certificate “Introducción a la gestión de resultados para
   el desarrollo” Banco Interamericano de Desarrollo (*BID*).
   - Honor code certificate “Global Health: Case Studies from a Biosocial
   Perspective” *Harvard* edX
   - Honor code certificate “Health and Society” *Harvard* edX
   - Honor code certificate “Unlocking the Immunity to Change: A New
   Approach to Personal Improvement” *Harvard* edX
   - Honor code certificate “Next Generation Infrastructures: Complexity,
   Governance and Regulation of Infrastructure Systems” *Delft University
   of technology*
   - Honor code certificate "Next Generation Infrastructures II Smart,
   Secure and Sustainable. Delft Univeristy of technology.
   - Honor code certificate "Future cities" ETH Zurich
   - Honor code certificate “Wiretaps to Big Data: Privacy and Surveillance
   in the Age of Interconnection” *Cornell Univeristy* edX
   - Honor code certificate “Behavioral Medicine: A Key to Better
Health” *Karolinska
   Institutet*.
   - “Becoming a Resilient Person: The Science of Stress Management and
   Promoting Wellbeing” *University of Washington* edX.
   - Diplomado en "Desarrollo de mercados, deuda pública y negociación de
   deuda" por el Instituto de capacitación de la ONU (UNITAR)
   - Diploma en PNL por el *ITESM*, seminario impartido por el PhD. John
   Grinder.
   - Especialista en Gestión ambiental urbana por la facultad de
   arquitectura de la *Universidad nacional del centro de Perú y las
   Fundación Fondo Verde*.
   - Diplomado en Planificación estratégica urbana por el *CIDEU*.
   - Experto en Administración y planificación pública (*INAP, INDESOL, UAM*
   )
   - Experto en Gobierno electrónico ( Sistema de capacitación de la *OEA*)
   - Experto en arbitraje por la UNITAR

Skype y Oovoo: salazar_joel
