### ISSUE TITLE
Still listed after installed and no Rename button present

### ISSUE THREAD

**Issue by ianme** [Chaosmeister/EAR#8]
Hi,

Everything in in the title: i install the plugin through the web interface but nothing happens. It is still not listed in the installed plugins (similar to #7) and there is no Rename button in the dropdown menu.

    Application version: 1.2.28
    PHP version: 8.1.17
    PHP SAPI: litespeed
    HTTP Client: cURL
    OS version: Linux 3.10.0-962.3.2.lve1.5.79.el7.x86_64
    Database driver: mysql
    Database version: 10.5.19-MariaDB-cll-lve
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0

Plugin version 1.1.2

Thank you.

**Comment by Chaosmeister** [comment]
Hi,
thanks for the hint!

I failed to update the release correctly. it's fixed now.

Unfortunately you need to delete the EAR directory from your plugins directory manually.

**Comment by ianme** [comment]
That's perfect, it works fine now.

Thank you for this nice plugin :-)
